Imbalanced Dataset:
A dataset with an unequal class distribution

In [19]:

# importung the dependencies
import numpy as np
import pandas as pd

In [20]:
# loading the dataset to pandas DataFrame
credit_Card_data = pd.read_csv('/content/creditcard.csv')

In [21]:
# first five rows of the dataframe
credit_Card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0.0
1,0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0.0
2,1,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0.0
3,1,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0.0
4,2,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0.0

In [22]:
credit_Card_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
37717,39076,1.117749,-1.544665,-0.145357,-1.307482,-1.392833,-0.630833,-0.563659,-0.038716,-2.173892,...,-0.334155,-1.108220,0.070461,0.115485,0.078726,-0.460844,-0.029143,0.029028,183.19,0.0
37718,39076,0.758729,-0.483875,0.125488,1.449159,-0.639231,-0.805011,0.406994,-0.221212,0.068777,...,0.210712,0.063091,-0.316636,0.394472,0.558720,-0.304812,-0.033008,0.063331,250.00,0.0
37719,39076,-0.474907,0.835804,0.075878,-1.251283,2.492736,3.385419,0.169507,0.934749,-0.584224,...,-0.270398,-0.866353,-0.085720,0.986274,-0.082934,0.084198,0.310936,0.170342,1.49,0.0
37720,39077,-2.682780,-2.028562,1.745223,-1.157952,-0.143692,-0.807503,-1.154141,0.436917,-0.293442,...,0.353396,0.968145,-0.776459,0.182662,-0.000427,-0.209058,0.256991,-0.585781,102.00,0.0
37721,39077,1.106292,-0.525727,0.926440,0.817696,-1.122177,-0.062703,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
# distribution of the two classes
credit_Card_data['Class'].value_counts()

Class
0.0    37618
1.0      103
Name: count, dtype: int64

This is Highly imbalanced dataset

0 -->  Legit Transaction and 1 --> Fraudulent Transaction

In [24]:
# Separating the legit and fraudulent transactions
legit = credit_Card_data[credit_Card_data.Class == 0]
fraud = credit_Card_data[credit_Card_data.Class == 1]

In [25]:
print(legit.shape)
print(fraud.shape)

(37618, 31)
(103, 31)

 Under Sampling

 Build a sample dataset containing similar distribution of Legit & Fraudulent Transactions

 No of Fraudulent Transactions --> 3

In [32]:
legit_sample = legit.sample(n = 103)

In [33]:
print(legit_sample.shape)

(103, 31)

Concatenate the two dataframes

In [34]:
new_dataset = pd.concat([legit_sample, fraud], axis = 0)

In [35]:
new_dataset.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
8808,12017,1.289971,-0.031192,0.407052,-0.158478,-0.300105,-0.194604,-0.439544,-0.026807,1.536601,...,-0.288060,-0.633478,-0.006597,-0.518604,0.158809,0.900906,-0.105966,-0.015486,8.00,0.0
32264,36715,1.207684,0.164638,-0.532487,1.335211,2.023235,3.959758,-0.798319,0.988799,-0.591408,...,0.091707,0.092227,-0.099253,1.004611,0.594652,0.111708,0.014392,0.024175,10.85,0.0
23437,32757,1.335053,0.331464,-2.057763,-0.346175,2.583234,2.854102,-0.187547,0.685154,-0.286614,...,-0.191820,-0.650118,-0.114069,0.915936,0.730073,0.383879,-0.031902,0.029849,0.76,0.0
3794,3307,0.223904,-2.026032,0.565840,0.523064,-1.622007,0.158617,-0.190473,0.115690,1.194065,...,0.194726,-0.380445,-0.329794,0.158347,-0.177578,0.970782,-0.117545,0.096279,500.00,0.0
8557,11522,1.098280,-0.688739,2.048801,0.903930,-1.747293,0.443075,-1.436737,0.252967,3.353517,...,-0.107760,0.414404,-0.102791,0.463789,0.259100,1.211659,-0.010732,0.017928,30.20,0.0

In [36]:
new_dataset.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
30442,35926,-3.896583,4.518355,-4.454027,5.547453,-4.121459,-1.163407,-6.805053,2.928356,-4.917130,...,1.691042,0.920021,-0.151104,0.011007,0.080303,0.412191,0.635789,0.501050,4.56,1.0
30473,35942,-4.194074,4.382897,-5.118363,4.455230,-4.812621,-1.224645,-7.281328,3.332250,-3.679659,...,1.550473,0.614573,0.028521,0.013704,-0.149512,-0.131687,0.473934,0.473757,14.46,1.0
30496,35953,-4.844372,5.649439,-6.730396,5.252842,-4.409566,-1.740767,-6.311699,3.449167,-5.416284,...,1.194888,-0.845753,0.190674,-0.216443,-0.325033,-0.270328,0.210214,0.391855,111.70,1.0
31002,36170,-5.685013,5.776516,-7.064977,5.902715,-4.715564,-1.755633,-6.958679,3.877795,-5.541529,...,1.128641,-0.962960,-0.110045,-0.177733,-0.089175,-0.049447,0.303445,0.219380,111.70,1.0
33276,37167,-7.923891,-5.198360,-3.000024,4.420666,2.272194,-3.394483,-5.283435,0.131619,0.658176,...,-0.734308,-0.599926,-4.908301,0.410170,-1.167660,0.520508,1.937421,-1.552593,12.31,1.0

In [38]:
new_dataset['Class'].value_counts()

Class
0.0    103
1.0    103
Name: count, dtype: int64